apiVersion: v1
kind: ServiceAccount
metadata:
  name: reporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reporter
subjects:
- kind: ServiceAccount	
  name: reporter
  namespace: default
roleRef:
  kind: ClusterRole 
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporter
  template:
    metadata:
      labels:
        app: reporter
    spec:
      serviceAccountName: reporter
      containers:
      - name: reporter
        #image: reporter:local
        image: 249575051361.dkr.ecr.us-east-1.amazonaws.com/tmp-reporter-romine:5
        imagePullPolicy: IfNotPresent
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: reporter
#  namespace: default
#spec:
#  type: NodePort
#  selector:
#    app: reporter
#  ports:
#  - port: 8080
#    targetPort: 8080
#    nodePort: 30001
