apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporter
  template:
    metadata:
      labels:
        app: reporter
    spec:
      containers:
      - name: reporter
        image: reporter:local
        imagePullPolicy: Never
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: reporter
#  namespace: default
#spec:
#  type: NodePort
#  selector:
#    app: reporter
#  ports:
#  - port: 8080
#    targetPort: 8080
#    nodePort: 30001
