#---
## Source: unsupervised/charts/postgres/charts/pgadmin/templates/ingress-pgadmin.yaml
#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: pgadmin-ingress
#  annotations:
#    kubernetes.io/ingress.class: "un1-nginx"
#    # nginx.ingress.kubernetes.io/rewrite-target: /$1
#    # nginx.ingress.kubernetes.io/use-regex: "true"
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      proxy_redirect off;
#      proxy_set_header X-Script-Name /console/pgadmin4;
#      proxy_set_header X-Forwarded-Proto $scheme;
#      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

#    nginx.ingress.kubernetes.io/auth-signin: https://localhost:30006/oauth2/authorize?client_id=102acc08-0257-42fd-a073-81ea2dfbd06f&response_type=code&redirect_uri=https%3A%2F%2Flocalhost%2Fauthorize
#    nginx.ingress.kubernetes.io/auth-method: GET
#    nginx.ingress.kubernetes.io/auth-url: http://un1-nginx-auth.un1-nginx.svc.cluster.local:8000/validate

#  labels:
#    app: pgadmin
#  #namespace: un1-postgres
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /console/pgadmin4
#        backend:
#          serviceName: pgadmin
#          servicePort: 80
